### PR TITLE
issue #29447 Move message handlers to qt-client and run login2 and other necessary…

### PR DESCRIPTION
**Pull request by ChristopherCotnoir**
… logic with autoRunArg

### CODE REVIEW

**Comment by ChristopherCotnoir** [comment]
Requires xtuple/qt-client#1570

**Comment by xtuple-ci-user** [comment]
Build finished.

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by xtuple-ci-user** [comment]
Build finished.

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by xtuple-ci-user** [comment]
Build finished.

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by gilmoskowitz** [comment]
ok jenkins, retest this please

**Comment by gilmoskowitz** [comment]
ok jenkins, retest this please

**Comment by gilmoskowitz** [comment]
ok jenkins, retest this please

**Pull request merged**
